global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

alerting: {}

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: "instance"

  - job_name: "vector"
    static_configs:
      - targets: ["vector:9095"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: "instance"
